### ISSUE TITLE
Description of intent, contents

### ISSUE THREAD

**Issue by linas** [opencog/TinyCog#3]
Can you please create a README file that describes:

* the purpose and goals of this project. 
* what sort of software is will be found/is supposed to be included here,
* what the software actually does
* what is currently in here (vs what is planned for the future)
* how it is used 
* any special or unusual hardware required

**Comment by linas** [comment]
Is it too late, or can we change the name to "EmbeddedRobots", or something like that, instead of OpenCogER?  Or how about these names:

* ERobots
* Roboto
* Robotoy
* Robomini
* Minirobo
* MiniCog
* MiniMind
* RoboMind
* MindToy
* RoboBrain

Ben is really good at making up names. "ER" in English is "Emergency Room" and OpenCogER sounds like OpenCog is on the verge of dying, its on life-support in the intensive-care unit of the hospital.  Either that, or a new TV show drama about OpenCog in the ER.

**Comment by Dagiopia** [comment]
hehe I can already imagine the opencog team running around in lab coats. 

it's an important note though. I like Roboto since we're workingon Dr Roboto now... esti let me ask on the slack channel and see what ben and the others think

**Comment by linas** [comment]
Two more:

* Robody
* Robosense.

Since its mostly about the actual body and sensory organs.  But Roboto is OK, given the current close ties to the toy.

**Comment by Dagiopia** [comment]
ben suggested tinycog so renamed it to that
